version: 2

jobs:
    # The test job
    build-and-test-front:
        working_directory: ~/mean/FrontMEAN/
        docker:
            - image: circleci/node:10-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout:
                path: ~/mean
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package-lock.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package-lock.json" }}
                paths:
                    - "node_modules"
            # Test the source code
            - run:
                name: Testing
                command: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
    build_and_test_back:
        working_directory: ~/mean/API-Back
        docker:
            - image: circleci/node:10.16.3
            - image: mongo:4.0
        steps:
            - checkout:
                path: ~/mean
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@5'
            - restore_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
            - run:
                name: install-npm-wee
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package-lock.json" }}
                paths:
                    - ./node_modules
            - run:
                name: start
                command: npm run start
            - run:
                name: test
                command: npm run test
            - run:
                name: stop-and-remove
                command: npm run rmdata

workflows:
    version: 2
    build_and_test:
        jobs:
        - build-and-test-front
        - build_and_test_back

